services:
  app_back_service:
    container_name: "app_back"

    build: .

    ports:
      - 8888:8000
    networks:
      - localNetwork
    env_file:
      - .envdocker

  app_redis_service:
    container_name: "app_redis"
    image: redis:latest
    ports:
      - 7379:6379
    networks:
      - localNetwork

  app_db_service:
    container_name: "app_db"
    image: postgres:17.6 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: house
    ports:
      - 6432:5432
    networks:
      - localNetwork
    volumes:
      - pg-data:/var/lib/postgresql/data 
    env_file:
      - .envdocker

networks:
  localNetwork:
    external: true

volumes:
  pg-data:
    driver: local

